"""create GreenOps history tables

Revision ID: 86f44edcf0e4
Revises: 
Create Date: 2026-09-25 23:35:29.481354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f44edcf0e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workload_name', sa.String(length=100), nullable=False),
    sa.Column('runtime_minutes', sa.Integer(), nullable=False),
    sa.Column('max_delay_hours', sa.Integer(), nullable=False),
    sa.Column('current_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_average_intensity', sa.Float(), nullable=False),
    sa.Column('recommended_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recommended_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recommended_average_intensity', sa.Float(), nullable=False),
    sa.Column('reduction_percent', sa.Float(), nullable=False),
    sa.Column('optimization_available', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workload_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workload_name', sa.String(length=100), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('runtime_hours', sa.Float(), nullable=False),
    sa.Column('requests_per_day', sa.Integer(), nullable=False),
    sa.Column('workload_type', sa.String(length=30), nullable=False),
    sa.Column('efficiency_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workload_analyses')
    op.drop_table('carbon_schedules')
    # ### end Alembic commands ###
